format = """
[](#464260)\
$os$username[@](bg:#464260 fg:#14131E)$hostname\
[](bg:#B0A8EB fg:#464260)\
$directory\
[](bg:#D9A1E8 fg:#B0A8EB)\
$git_branch$git_commit$git_state$git_metrics$git_status\
[](bg:#EBB17B fg:#D9A1E8)\
$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam\
$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs\
$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust\
$scala$solidity$swift$terraform$typst$vlang$vagrant$zig\
[](bg:#C8D5F1 fg:#EBB17B)\
$cmd_duration\
[](fg:#C8D5F1)\
$line_break\
$character
"""

# EXCLUDED $
# ==========
# to add later if I need them lmao
# localip, shlvl, singularity, kubernetes
# vcsh, fossil_branch, fossil_branch_metrics, hg_branch, pijul_channel, docker_context
# buf, nix_shell, conda, meson, spack
# memory_usage
# aws, gcloud, openstack, azure
# direnv, env_var, crytal, custom, sudo
# jobs, status, container, shell

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#14131E bg:#D9A1E8"

[git_commit]
style = "fg:#14131E bg:#D9A1E8"

[git_state]
style = "fg:#14131E bg:#D9A1E8"

[git_metrics]


[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "fg:#14131E bg:#D9A1E8"

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#14131E bg:#EBB17B"

[python]
symbol = '󰌠 '
format = "[ $symbol($version )]($style)"
style = "fg:#14131E bg:#EBB17B"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#14131E bg:#464260"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#14131E bg:#464260"
disabled = false

[os.symbols]
Arch = ' '

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#14131E bg:#464260"

[directory]
style = "fg:#14131E bg:#B0A8EB"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#14131E bold bg:#B0A8EB"

[sudo]
disabled = false
symbol = " "
style = "fg:#14131E bg:#C8D5F1"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#14131E bg:#C8D5F1"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"
